lib/config.ts

* Let the bin file decide which webdriver-manager to use
* Use the configuration file / package from the default position
* Selenium folder will always be located to webdriver-manager/selenium/

fix(config): simplify locating configuration file, selenium folder

---

lib/files/downloader.ts

- 'code' and 'connect' is not defined as part of the 'error' type declaration
- setting error to any prevents this transpile error

chore(downloader): set error type to any

---

.gitignore
config.json
lib/binaries/gecko_driver.ts
lib/binaries/ie_driver.ts
lib/binaries/index.ts
lib/cmds/opts.ts
lib/cmds/start.ts
lib/cmds/update.ts
lib/config.ts
lib/files/file_manager.ts
tsconfig.json

geckodriver is still a little experimental, so I've disabled it by default. You need "marionette: true" in your capabilities in order to use it. Also, there's a bug where after we delete the session at the end of the test, geckodriver won't run again so you need to restart selenium.

Add geckodriver, related config, and flags.

---

lib/binaries/android_sdk.ts
lib/binaries/appium.ts
lib/binaries/binary.ts
lib/binaries/chrome_driver.ts
lib/binaries/gecko_driver.ts
lib/binaries/ie_driver.ts
lib/binaries/stand_alone.ts
lib/cmds/update.ts
lib/files/file_manager.ts
spec/files/fileManager_spec.ts

fix(filemanager): Binaries can be downloaded from a custom CDN

---

lib/cmds/update.ts
lib/files/file_manager.ts

Using `--ignore_ssl` option can work around [UNABLE_TO_GET_ISSUER_CERT_LOCALLY error](https://gist.github.com/royling/b8281915a76792ba54626dcfe39ecf24), that could be encountered in a corporate network. But this only works at a fresh run, the subsequent run failed.
That's because the proxy/ignoreSSL options are not passed in `Downloader.httpHeadContentLength()`, which is to fire a HEAD request for content-length field for size checking.
This change fixed the problem.

fix(filemanager): respect proxy/ignoreSSL options in httpHeadContentLength

---

lib/cli/cli.ts
lib/cli/options.ts
lib/cli/programs.ts

- default option values initialize properly for `minimist`
- user-supplied boolean-type option values respected
- string-type option values are always strings
- simplify boolean-type option value access

fix(cli): fix default option values, boolean and string handling (#110)

---

lib/cli/options.ts
lib/cli/programs.ts
spec/cli/options_spec.ts
spec/cli/programs_spec.ts
spec/webdriver_spec.ts

- This fixes `webdriver-manager update --gecko=false`
- This does not fix `webdriver-manager update --gecko=0`. Minimist interprets 0 as true.
closes #110

fix(cli): fix setting flag to false

---

gulpfile.js
lib/cli_instance.ts
lib/cmds/start.ts
lib/utils.ts
lib/webdriver.ts
spec/cli/programs_spec.ts
spec/files/downloader_spec.ts
spec/files/fileManager_spec.ts
spec/webdriver_spec.ts

* In the rebase of 232946b against 1f9713a, an unwrapped `spawn()` was introducted
* This unwrapped `spawn()` required that our internal `spawn()` needed a fix to its signature
* There was also an unwrapped `spawn()` in `spec/webdriver_spec.ts`
* While fixing that, I got annoyed with the console output `spec/webdriver_spec.ts` produces so I
refactored it away
* I also noticed that clang wasn't running against the spec files, and fixed that
* I also ran clang against the spec files

chore(infrastructure): Fixed a few minor, related-ish problems

---

lib/files/downloader.ts

… Otherwise we won’t terminate until the whole file was downloaded, even though we don’t need it.
This patch reduces the time required for `webdriver-manager update` on an up-to-date installation from more than 5 seconds to less than 2 seconds on my machine (when updating `standalone`, `gecko` and `chrome`).
Btw: It's still wasteful to run `httpHeadContentLength` and then `downloadBinary` in case we're outdated – since the former already starts downloading. It might be better to start the request, wait for the headers and then either continue or abort – instead of always throwing away the first request and then starting over again.

`httpHeadContentLength`: Destroy the request after receiving the header

---

.travis.yml
package.json
tsconfig.json

- with node 6 on LTS, we can update the tsconfig to es6
- update travis tests to use node 6 and 7

chore(es6): allow to use es6 promises

---

lib/cmds/update.ts
lib/files/downloader.ts
lib/files/file_manager.ts
spec/files/downloader_spec.ts
spec/files/fileManager_spec.ts

- add method to downloader to getFile
- add method to file manager to use new downloader getFile
- rewrite updateBinary function to use new file manager method
- add a couple of unit tests around downloader getFile
- use es6 promises, change travis to use node 6 minimum
- remove old method to request file in file manager and downloader

chore(downloader): replace workflow with a single request

---

lib/cmds/opts.ts
lib/cmds/shutdown.ts

When scripting, you might want to defensively run a `shutdown` command.  If the shutdown fails
because the server is already off, you don't care.  If it fails for another reason, you do care.
So I made trying to shutdown a server which is already off just a warning.  I added a flag in case
you want the old behavior though.

feat(shutdown): do not error if you try to shutdown a server which is already off

---

lib/binaries/android_sdk.ts
lib/cmds/opts.ts
mobile.md

The default was x86-64, but x86 cannot be emulated on ARM.  This makes more sense

feat(android): match android arch to os.arch

---

lib/binaries/android_sdk.ts
lib/cmds/start.ts
lib/utils.ts

Before, we were just waiting for the emulator to be running, rather than waiting for the OS to be
booted up and ready to instance chrome.
While I was doing that I moved some stuff into `lib/utils.ts` since I felt like too much of
`lib/cmds/start.ts` was being devoted to this one feature.
Additionally, `--started-signifier` wasn't sending anything to the console, so I fixed that too (see https://github.com/angular/webdriver-manager/issues/166)

fix(start): wait for emulated android to really be ready before signaling

---

.npmignore
.travis.yml
e2e_spec/browser_spec.ts
e2e_spec/server_spec.ts
e2e_spec/support/headless.json
e2e_spec/support/jasmine.json
e2e_spec/target_browsers.ts
gulpfile.js
package.json

Travis only runs a subset of tests via `npm run test_travis`, but `npm test` runs a full suite.
See angular#165 for details on why travis cannot run all tests.

chore(tests): e2e tests

---

.gitignore
gulpfile.js
lib/cli/programs.ts
lib/cmds/update.ts
lib/files/downloader.ts
lib/files/file_manager.ts
lib/utils.ts
package.json
spec/cmds/update_spec.ts
spec/files/downloader_spec.ts

This feature will help directConnect users for Protractor. The file
will keep track of the last binary version as well as all other
binaries downloaded.
The file will be created in the output directory. By default this is
`selenium/update-config.json`
```
webdriver-manager update --versions.chrome=2.20 --standalone=false
--gecko=false
```
file created:
```
{
"chrome": {
"last": "/opt/src/webdriver-manager/selenium/chromedriver_2.20",
"all": ["/opt/src/webdriver-manager/selenium/chromedriver_2.20"]
}
}
```
then the user wants to use 2.25:
```
webdriver-manager update --versions.chrome=2.25 --standalone=false
--gecko=false
```
file created:
```
{
"chrome": {
"last": "/opt/src/webdriver-manager/selenium/chromedriver_2.25",
"all": ["/opt/src/webdriver-manager/selenium/chromedriver_2.20", …
```

feat(update): on update, write full binary paths to file

---

lib/cmds/start.ts

- clang formatting
closes #147

fix(iedriver): if downloading x64, use x64 version on start command

---

lib/binaries/android_sdk.ts
lib/binaries/appium.ts
lib/binaries/binary.ts
lib/binaries/chrome_driver.ts
lib/binaries/gecko_driver.ts
lib/binaries/ie_driver.ts
lib/binaries/stand_alone.ts
lib/cmds/initialize.ts
lib/cmds/opts.ts
lib/cmds/start.ts
lib/cmds/status.ts
lib/cmds/update.ts
lib/files/file_manager.ts
spec/cmds/status_spec.ts

fix(ie): Use 32-bit version by default for IEDriver

---

lib/binaries/config_source.ts

When the Github API limit is reached, the error message now directly informs
the user.  Also, when any other failure occurs the status code is reported.
This should hopefully give more info for issue #216.

feat(gecko): Improve error message when Github api limit reached.

---

lib/binaries/binary.ts
lib/binaries/chrome_xml.ts
lib/binaries/config_source.ts
lib/binaries/gecko_driver_github.ts
lib/binaries/iedriver_xml.ts
lib/binaries/standalone_xml.ts

In previous fix(#208), the option was not passing to config source.
closes #207.

fix(ignoressl): pass option to both binary and config source

---

lib/binaries/binary.ts
lib/binaries/config_source.ts
lib/cmds/update.ts
lib/files/downloader.ts
lib/files/file_manager.ts
lib/http_utils.ts

Since these options are for every request in the update command, it's not necessary to explicitly pass them down to irrelevant instances (eg. binaries and config sources).

refactor(binaries): remove proxy/ignoreSSL opts from binary/config source

---

lib/binaries/config_source.ts
lib/files/file_manager.ts
spec/binaries/config_source_spec.ts

- on clean, remove responses
- on update, if the size is 0 then get a new response

fix(responses): response xml and json files

---

lib/files/file_manager.ts

webdriver-manager clean does not remove chrome.xml. The metaFiles reference has a different name chromedriver-response.xml in the list causing the problem.
This PR will address that issue.

Fix: webdriver clean

---

lib/binaries/config_source.ts
lib/files/file_manager.ts
package-lock.json
spec/binaries/config_source_spec.ts
spec/cli/options_spec.ts
spec/files/downloader_spec.ts
spec/files/file_manager_spec.ts

It looks like the code hasn't been touched since October, but when I attempted to `npm install` this, I ran into a few failures that had to be fixed. Using nvm I versioned back to the what I believe is currently used in the circleci pipeline, v6.1.0. Still encountered failure.
I didn't look too far into it, but I think that a dependency might have changed to cause the new failures. To (hopefully) prevent this in the future, I also took the opportunity to add the package-lock.json file that was generated with the latest nodejs LTS.

Build fixes and package-lock.json addition

---

README.md

- update the circle ci badge to point to the 'replacement' branch
- improve documentation around using webdriver-manager as a dependency
- remove wording about "webdriver-manager-replacement"

docs(dep): improve docs when used as a dependency

---

README.md

Was going to fix the typo in the sentence `It will not work for these since Protractor is looking files downloaded locally to the project.` in the README ("Protractor is looking files"), but I thought this rewording might be a little more clear.

Updated readme for clarity.

---

lib/binaries/standalone_xml.ts
package-lock.json

This fix is here because selenium now has .zip files in the .xml. This
worked previously since there were no .zip files and it would find the
first version that matched the latest jar file.
Fix for legacy branch to update.
Closes #370

fix(selenium): download jar files and not zip files

---

lib/binaries/chrome_xml.ts

Versions of Chromdriver were versioned as 2.xx. We previously used to
tack on a '.0' at the end to make it a semver version. This is why it
was not downloading 74.0.3729.6. We now have to change 74.0.3729.6 to be
a semver. We will do this by grabbing 74.0.3729 with a regex.
This should work when downloading the latest chromedriver version since
2.46.0 < 74.0.3729. If Chromedriver releases 75 but we are still on
Chrome 74, this will still break in this version of webdriver-manager.
This does not prevent latest Chromedriver and latest Chrome mismatches.
If you run into an issue where Chromedriver is mismatched with Chrome,
use the --versions.chrome flag to pass in the version to download.

fix(chromedriver): support downloads for chromedriver beyond 2.46

---

config.json
lib/binaries/chrome_xml.ts
lib/cmds/status.ts
lib/config.ts

- Set the max versioning set in config.json. This will need to be updated on
every release of chromedriver. This will "fix" chrome and chromedriver
mismatches until Chrome 75 comes out. When it does there will have to be
an update for this again. Possible future work would allow a user
to set this via flag. Example --maxVersions.chrome "74."
- Create a generic way to get a valid version for Chromedriver. If
presented with 2.x, change this to 2.x.0. If presented with a 74.x.x.x,
chop off the last set of numbers and change this to 74.x.x
- Fixes the status command during a semver check.
- Fixes the update and start command when starting a specific version of
chromedriver

fix(chromedriver): version fixes for update, status, and start

---

lib/cli/index.ts
lib/cmds/utils.ts

During the rewrite, changing the port was supported; however, the seleniumPort flag was not added to the cli.
closes #360

fix(seleniumPort): add seleniumPort flag

---

lib/cli/index.ts
lib/cmds/options.ts
lib/cmds/start.ts
lib/cmds/utils.ts
lib/provider/selenium_server.ts

chore(selenium): add selenium.LOGGER.level flag when starting the server

---

lib/provider/chromium.spec-int.ts
lib/provider/chromium.ts
lib/provider/utils/cloud_storage_xml.ts
lib/provider/utils/file_utils.ts
spec/jasmine-int.json

Experimental feature to download the chromium browser based on the
ChromeDriver version. This might be help to prevent browser / browser
driver mismatch when downloading ChromeDriver. In the new scenario, you
could download ChromeDriver 73.x.x.x and Chromium 73.

feat(chromium): download the chromium binary based on a major version

---

lib/cli/index.ts
lib/cmds/cmds.spec-e2e.ts
lib/cmds/options.ts
lib/cmds/update.ts
lib/cmds/utils.spec-unit.ts
lib/cmds/utils.ts
lib/provider/chromedriver.ts
lib/provider/geckodriver.ts
lib/provider/iedriver.ts
lib/provider/provider.ts
lib/provider/selenium_server.ts
lib/provider/utils/version_list.spec-unit.ts
lib/provider/utils/version_list.ts

- Do a version match based on string startsWith of the maxVersion
An example:
Matching "0.1" might find versions 0.14.0, 0.151.0, 0.1.0. It will then
get the max version which is 0.151. If a user wanted to get 0.1, then
they could specify version "0.1."
- Fix / update interchangable aliases:
- selenium == standalone
- chromedriver == chrome
- geckodriver == gecko
- iedriver = ie
Tagging #280, #358, #353. Additional work is still required to have a
config file that has this information instead of hard coding it.

feat(max_versions): set max versions based on string matching

---

lib/cli/index.ts
lib/cmds/options.ts
lib/cmds/utils.spec-unit.ts
lib/cmds/utils.ts
lib/index.ts
lib/provider/chromium.ts
lib/provider/utils/file_utils.ts

Most of these methods do not work with Windows and there still needs to
have some tests against the chromium.ts file.
- provide hooks when used in cli and as a node module
- fix update to only have one version of chromium
- add methods to get the binary file from the chromium.config.json
- add clean and status methods

chore(chromium): add chromium to cli and lib

---

config.json

See: https://chromereleases.googleblog.com/2019/09/stable-channel-update-for-desktop.html

Updates maxChromedriver to 77

---

lib/binaries/chrome_xml.ts
lib/http_utils.ts
spec/binaries/chrome_xml_spec.ts
spec/binaries/standalone_xml_spec.ts
spec/cmds/status_spec.ts
spec/cmds/update_spec.ts
spec/files/downloader_spec.ts

This ports over (some of) the changes @cnishina has made in the download_stable branch to the legacy branch along with a little clean up of the exports along the way.

Get latest fix

---

lib/binaries/chrome_xml.ts
spec/binaries/chrome_xml_spec.ts

Attempt to fix #472 - with more context specifically at https://github.com/angular/webdriver-manager/issues/472#issuecomment-685225125

fix(chromedriver): get most recent version on x64 windows if multiple major versions exist
