angular/webdriver-manager

.travis.yml

chore(test): add a travis yml file

---

.npmignore
README.md

chore(readme): reference pose/webdriver-manager for previous versions

---

lib/cmds/start.ts
lib/cmds/status.ts
lib/files/file_manager.ts

fix(dir): check selenium dir and warn user that the folder does not exist

---

bin/webdriver-manager
lib/config.ts

chore(config): fix when installed as dependency

---

lib/config.ts

fix(config): configuration file local look up when used as a dependency

---

config.json
lib/binaries/appium.ts
lib/binaries/index.ts
lib/cmds/initialize.ts
lib/cmds/opts.ts
lib/cmds/start.ts
lib/cmds/update.ts
lib/config.ts
lib/files/file_manager.ts
mobile.md
spec/files/fileManager_spec.ts

Closes https://github.com/angular/webdriver-manager/issues/47 and https://github.com/angular/webdriver-manager/issues/48

feat(ios): iOS support/split appium out

---

lib/cmds/start.ts

fix(start): use ie32 if specified via command line

---

lib/files/downloader.ts

fix(downloader): increase timeouts and unlink sync on download errors

---

lib/cmds/opts.ts
lib/cmds/start.ts

feat(logging): add logging property to selenium standalone

---

lib/cmds/update.ts

fix(update): download standalone with proxy and ignore ssl

---

config.json

chore(chromedriver): update chromedriver version to 2.23

---

config.json

Chromedriver < 2.24 has issues with Chrome 54+ (https://bugs.chromium.org/p/chromedriver/issues/detail?id=1451).

chore(chromedriver): update chromedriver version to 2.24

---

lib/binaries/chrome_driver.ts
package.json

fix(chrome_driver): use the x64 binary if chrome driver version is greater than 2.23

---

CHANGELOG.md
browsers.md
lib/cmds/start.ts
package.json

- supported browsers markdown
- update jar file command order
- typing dependency outdated bump

chore(release): version bump and update changelog

---

lib/cmds/start.ts

fix(start): set the port when standalone server starts

---

lib/cmds/update.ts

fix(update): fix undefined gecko getBoolean error

---

CHANGELOG.md
config.json
package.json

- update changelog and version for 11.0.0-beta.0
closes #109

chore(config): update config to selenium standalone server 3

---

spec/files/downloader_spec.ts

Line 32, type in describe string.
(This is my first pull request for OSS! I'll fix anything I've left out in the contribution process.)

fix typo in webdriver-manager/spec/files

---

config.json
lib/binaries/android_sdk.ts
lib/cmds/initialize.ts
lib/cmds/opts.ts
lib/cmds/start.ts
lib/cmds/update.ts
mobile.md
spec/files/fileManager_spec.ts

- Make appium default to 1.6.0 (Android N didn't work on 1.5.x)
- Make virtual devices default to `google_apis`
- Don't delete old virtual devices on update
- Update documentation

fix(android): fixed like a million things for android

---

config.json
lib/binaries/gecko_driver.ts
lib/cmds/update.ts

fix(gecko): Update geckodriver to 0.11.0 and fix suffixes.

---

lib/files/downloader.ts

fix(gecko): follow redirects for content-length

---

lib/cmds/version.ts
lib/webdriver.ts

feat(version): have a way to get the package version

---

gulpfile.js
lib/binaries/android_sdk.ts
lib/binaries/appium.ts
lib/cmds/initialize.ts
lib/cmds/start.ts
lib/cmds/update.ts
lib/utils.ts

Part 1 of making android/appium work on windows

chore(windows): make spawn() calls more cross platform

---

.travis.yml
gulpfile.js
package.json
tsconfig.json

- update outdated dependencies
- remove format from prepublish and enforce this check on travis
- add scripts for format and check_format on package.json
- update tsconfig

chore(project): upgrade dependencies, enforce format in travis

---

.npmignore

Removes the editor specific files from the published files

publish: remove .idea folder from dist

---

lib/cmds/opts.ts
lib/cmds/start.ts
package.json
tsconfig.json

The next installment of my long running "make it easier to everything in a script" series

feat(start android): extend the --detach flag to wait for appium/android

---

lib/binaries/android_sdk.ts
lib/cmds/initialize.ts
lib/cmds/start.ts
lib/cmds/update.ts
lib/files/downloader.ts
lib/files/file_manager.ts

Found while debugging windows.

fix(fs): `path.join` does not handle absolute paths as desired

---

lib/cmds/initialize.ts
lib/cmds/start.ts
lib/cmds/update.ts

Closes https://github.com/angular/webdriver-manager/issues/51

feat(android on windows): Support android VMs on windows

---

config.json

* Recently a new version of the chrome-driver has been released (v2.26).
It includes a lot of fixes for the latest Chrome version.
https://sites.google.com/a/chromium.org/chromedriver/downloads
FYI: Didn't touch the `browsers.md` in favor of https://github.com/angular/webdriver-manager/pull/174

chore: update to latest chrome driver

---

lib/cmds/initialize.ts
lib/cmds/opts.ts
lib/cmds/status.ts
lib/cmds/update.ts
spec/cmds/status_spec.ts

- added a test to run update, then checks status for labels
closes #172

feat(status): show the last downloaded version when using status

---

config.json
lib/cmds/start.ts

Also bump the geckodriver version to latest.

fix(gecko): Respect versions.gecko in start command

---

circle.yml

chore(ci): Install latest Chrome on CircleCI

Install latest Chrome on CircleCI

---

README.md

Was implemented here
https://github.com/angular/webdriver-manager/commit/338fffddf68ac2767aa5c226ba5374451b9e5308

Documentation for running driver on background

---

.gitignore
e2e_spec/android_spec.ts
lib/binaries/binary.ts
lib/binaries/chrome_xml.ts
lib/binaries/config_source.ts
lib/binaries/gecko_driver_github.ts
lib/binaries/iedriver_xml.ts
lib/binaries/standalone_xml.ts
lib/files/file_manager.ts
package.json

fix(ignoressl): pass ignore ssl down to the binary and config source

---

lib/binaries/config_source.ts

fix(cache): change timestamp to 1 hour instead of 10 hours

---

config.json

The 1.6.0 released 7 months ago - there are many new features available.

Bump up the appium version

---

lib/cmds/start.ts

See issue https://github.com/angular/webdriver-manager/issues/227

Change appiumPort to seleniumPort for selenium server request

---

spec/server/http_server.ts

**fix([spec](https://github.com/angular/webdriver-manager/blob/master/spec/server/http_server.ts)) : Fix isFile or isDirectory check**
- Fix the `isDirectory()` check by adding `()` to call the function.
- Remove empty `if` branch by refactoring condition @ [line 16](https://github.com/angular/webdriver-manager/pull/350/files#diff-a80618d05e5230a85440875415430988R16)

Fix isFile or isDirectory check

---

README.md

Adding a note explaining the issue.

chore(readme): incoherence between ChromeDriver and Chrome latest versions

---

lib/provider/appium.ts
lib/provider/chromedriver.ts
lib/provider/geckodriver.ts
lib/provider/iedriver.ts
lib/provider/provider.ts
lib/provider/selenium_server.ts

- override the default variable with the npmrc value
- if a flag is set, then use the value
- implement a provider class to extend from
closes #189

chore(npmrc): allow to use npmrc for flags

---

lib/provider/chromedriver.spec-proxy.ts
lib/provider/utils/http_utils.spec-int.ts
lib/provider/utils/http_utils.spec-proxy.ts
lib/provider/utils/http_utils.ts

fix(proxy): if the proxy is http, edit the request url

---

README.md

chore(docs): add legacy doc references for < 12

---

lib/binaries/chrome_xml.ts
spec/binaries/chrome_xml_spec.ts

fix(binaries): filter m1 mac chromedriver versions
